-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. USERS TABLE (Required for foreign keys)
CREATE TABLE IF NOT EXISTS users (
  id bigint generated by default as identity primary key,
  email text unique not null,
  password text not null,
  name text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. CONTACTS TABLE
CREATE TABLE IF NOT EXISTS contacts (
  id uuid default uuid_generate_v4() primary key,
  user_id bigint references users(id) not null,
  waba_id text not null,
  phone_number text not null,
  name text,
  email text,
  tags text[] default array[]::text[],
  attributes jsonb default '{}'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, phone_number)
);

CREATE INDEX IF NOT EXISTS contacts_user_id_idx ON contacts(user_id);
ALTER TABLE contacts ENABLE ROW LEVEL SECURITY;

-- 3. MESSAGES TABLE
CREATE TABLE IF NOT EXISTS messages (
  id uuid default uuid_generate_v4() primary key,
  user_id bigint references users(id) not null,
  waba_id text not null,
  phone_number_id text not null,
  contact_id uuid references contacts(id),
  wa_message_id text unique,
  direction text check (direction in ('inbound', 'outbound')) not null,
  type text not null,
  body text,
  media_url text,
  status text default 'sent', 
  timestamp timestamp with time zone default timezone('utc'::text, now()) not null,
  raw_data jsonb
);

CREATE INDEX IF NOT EXISTS messages_contact_id_idx ON messages(contact_id);
CREATE INDEX IF NOT EXISTS messages_user_id_idx ON messages(user_id);
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;

-- 4. CAMPAIGNS TABLE
CREATE TABLE IF NOT EXISTS campaigns (
  id uuid default uuid_generate_v4() primary key,
  user_id bigint references users(id) not null,
  name text not null,
  template_name text,
  template_language text default 'en_US',
  status text default 'draft',
  scheduled_at timestamp with time zone,
  audience_filter jsonb default '{}'::jsonb,
  stats jsonb default '{"sent": 0, "delivered": 0, "read": 0, "failed": 0}'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE INDEX IF NOT EXISTS campaigns_user_id_idx ON campaigns(user_id);
ALTER TABLE campaigns ENABLE ROW LEVEL SECURITY;

-- 5. AUTOMATION FLOWS TABLE
CREATE TABLE IF NOT EXISTS automation_flows (
  id uuid default uuid_generate_v4() primary key,
  user_id bigint references users(id) not null,
  name text not null,
  trigger_keyword text,
  flow_data jsonb default '{}'::jsonb,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE INDEX IF NOT EXISTS automation_flows_user_id_idx ON automation_flows(user_id);
ALTER TABLE automation_flows ENABLE ROW LEVEL SECURITY;

-- 6. WHATSAPP ACCOUNTS TABLE (Inferred from db-supabase.js usage)
CREATE TABLE IF NOT EXISTS whatsapp_accounts (
  id uuid default uuid_generate_v4() primary key,
  user_id bigint references users(id) not null,
  waba_id text not null unique,
  phone_number_id text not null,
  access_token text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 7. DISABLE RLS (Fix for "uuid = bigint" error and backend compatibility)
-- The backend uses a custom auth system and `anon` key, so strict RLS policies dealing with Supabase Auth UUIDs cause issues.
-- We disable RLS enforcement so the backend queries (which filter by user_id manually) can work.

ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE contacts DISABLE ROW LEVEL SECURITY;
ALTER TABLE messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE campaigns DISABLE ROW LEVEL SECURITY;
ALTER TABLE automation_flows DISABLE ROW LEVEL SECURITY;
ALTER TABLE whatsapp_accounts DISABLE ROW LEVEL SECURITY;

-- Clean up any potentially conflicting policies just in case
DROP POLICY IF EXISTS "Users can view their own contacts" ON contacts;
DROP POLICY IF EXISTS "Users can insert their own contacts" ON contacts;
DROP POLICY IF EXISTS "Users can update their own contacts" ON contacts;
DROP POLICY IF EXISTS "Users can delete their own contacts" ON contacts;
